Feat/seekup 7 login page
Dreher-Dev/app.projeto-arroba pull request #1
Opened 2023-11-29 19:25 UTC by vaz-rh

2023-11-30 15:52 UTC, mateusdreher requested changes

2023-11-30 15:52 UTC, mateusdreher commented on src/components/CompoentExample/ComponentExample.js
> -import css from './ComponentExample.module.css';
Remove esse componente

2023-11-30 15:52 UTC, mateusdreher commented on src/components/CompoentExample/ComponentExample.module.css
> -.classExample {
Remove esse componente

2023-11-30 15:52 UTC, mateusdreher commented on src/components/FormLogin/FormLogin.js
> +                <Form.Group  className={style.containerFormDiv}controlId="formBasicCheckbox">
Pra que serve esse controlId="formBasicCheckbox"?

2023-11-30 15:52 UTC, mateusdreher commented on src/components/FormLogin/FormLogin.js
> +                <Button className={style.containerFormButton} variant="primary" disabled={email === '' || password === ''}  onClick={validateUserCredentials}>
Passa essa validação do disabled para uma função que retorne um boolean e chama a função aqui.

2023-11-30 15:52 UTC, mateusdreher commented on src/components/FormLogin/FormLogin.js
> +                <Form className={style.containerFormConta}>
muda o nome da classe, mantém tudo em inglês. Pode ser um `containerFormAccount`

2023-11-30 15:52 UTC, mateusdreher commented on src/components/Imagem/Imagem.js
> +            <img src="/assets/imgs/imgLogin.png" alt="qualquer coisa" className="imagem"/>
Descreve a imagem no alt

2023-11-30 15:52 UTC, mateusdreher commented on src/components/Traco/Traco.js
>  export function Traco() {
Nomes sempre em ingles, muda o nome do componente para inglês. Pode ser `verticalLine` ou algo assim

2023-11-30 15:52 UTC, mateusdreher commented on src/components/Traco/Traco.module.css
> -.traço {
Mesma coisa, tudo em ingles

2023-11-30 15:52 UTC, mateusdreher commented on src/pages/Login/Login.module.css
> +.containerTraco {
Tudo em ingles

2023-11-30 15:52 UTC, mateusdreher commented on src/pages/Login/Login.js
> +                    <Imagem/>
Tudo em ingles, o nome do componente deve ser `Image`

2023-12-04 17:32 UTC, vaz-rh commented on src/components/CompoentExample/ComponentExample.js
> -import css from './ComponentExample.module.css';
Já foi removido.

2023-12-04 17:32 UTC, vaz-rh commented on src/components/CompoentExample/ComponentExample.module.css
> -.classExample {
Já foi resolvido.

2023-12-04 18:00 UTC, mateusdreher approved these changes
LGTM

2023-12-04 18:01 UTC, merged